/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trabalho;

public class App {
   

    public static void main(String[] args) {
      App aplicacao =  new App();
      pessoa p1 = new pessoa("gabriel");
      piloto pil = new piloto("alves");
      carro um = new carro("Mercedes");
      
    }
}
